### ISSUE TITLE
Voice Chat system is not working correctly

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/kernel#339]
## Description
After doing several tests with several people, we have reached the conclusion that something in Kernel side broke the Voice Chat in some point and it is not related to .zone or .org as we though at the beginning. We have found some cases (like @olavra) where this Voice Chat issue is happening ALWAYS:

1. He try to activate the microphone clicking the microphone button.
2. The browser ask about the needed mic permissions and he allows them.
3. From this point on, the microphone button keeps indefinitely pressed  but he never receives any update from Kernel. All the voice chat system seems to be totally deactivated and he can't send audio neither receive it from anyone.

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/1f65a711-6663-46c9-8d24-3decd0dd0abc)

However for other users (like @sandrade-dcl) the Voice Chat is working perfectly... it is very weird.

We have also checked it doesn't mind if the test is done from Mac or from Windows, if it is .org or .zone... we have gotten different results depending the user.

## Acceptance criteria
- [ ] The Voice Chat system should work fine for all users.

**Comment by Suduck** [comment]
For me, it works from the UI perspective, however, people from around me can't hear me
