### ISSUE TITLE
Dedup status updates per user

### ISSUE THREAD

**Issue by moliva** [decentraland/kernel#504]
[Kernel is sending a big number of user presence updates](https://grafana.decentraland.systems/d/K-UJF8z4z/miscellaneous-kernel-renderer-calls-metrics?orgId=1&var-counterName=All&from=now-7d&to=now) to renderer with duplicated state.

We need to understand if Matrix is duplicating the presence updates and if so understand how to simplify this from the producer side or possibly find a way to avoid sending duplicated data to the renderer.

**Comment by Julieta11** [comment]
we may have a hint [here](https://github.com/decentraland/kernel/blob/8e0e9b837797bb409fa2998952ae2456c253c4eb/packages/shared/friends/sagas.ts#L798-L840):

+ we get all [user's friends](https://github.com/decentraland/kernel/blob/8e0e9b837797bb409fa2998952ae2456c253c4eb/packages/shared/friends/sagas.ts#L815).
+ we call the [updateUserStatus](https://github.com/decentraland/kernel/blob/8e0e9b837797bb409fa2998952ae2456c253c4eb/packages/shared/friends/sagas.ts#L819) func and pass it an array with the friendIds (all of them).
+ the [updateUserStatus](https://github.com/decentraland/kernel/blob/8e0e9b837797bb409fa2998952ae2456c253c4eb/packages/shared/friends/sagas.ts#L790-L796) func gets the statuses of all friends and sends the updates to unity.
