### ISSUE TITLE
Sometimes user A can see everyone but other users cannot see user A

### ISSUE THREAD

**Issue by pablitar** [decentraland/kernel#78]
We have observed some cases in which there is people that can see everyone and that seem connected to the P2P network, but other people cannot see them.

Previously we've seen that this happened when a profile couldn't be loaded correctly. Preliminary investigation seems to indicate there is something wrong in the logic that loads profiles:
- The user that couldn't be seen did appear in the "known peers" of the peer library, and its stats seemed to indicate that messages were being received. This was checked using https://peer.decentraland.org/comms/peers to translate the user's address to a peer id, and seeing the known peer `Object.values(__DEBUG_PEER.knownPeers).find(it => it.id === "${user's id}")`
- The user's profile didn't appear in the global store. This was checked using: `globalStore.getState().profiles.userInfo["${user's address}".toLowerCase()]`

This seems to indicate that the profile couldn't be loaded, and for some reason is not being retried either.

**Comment by pravusjif** [comment]
It's worth mentioning that when this happens, the "invisible user" can be heard through the voice chat. We saw this yesterday trying a daily meeting with the team in-world.
